# Generated by Django 4.0.4 on 2022-06-08 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='datetime',
            field=models.DateField(auto_now_add=True),
        ),
    ]
