# Generated by Django 4.0.4 on 2022-06-08 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_bio_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='datetime',
            field=models.DateField(default='07-06-2022'),
        ),
    ]
