# Generated by Django 4.0.4 on 2022-06-08 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_bio_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bio',
            name='datetime',
        ),
    ]
